baseurl = "https://yuzu-emu.org/"
languageCode = "en-us"
languageCode = "pt-br"
DefaultContentLanguage = "en"
theme = "shared-bulma-theme"

# Define how many objects appear per pagination.
paginate = 20

[[menu.main]]
  name = "blog"
  weight = 1
  identifier = "blog"
  url = "/"

[[menu.main]]
  name = "download"
  weight = 2
  identifier = "download"
  url = "/downloads"

[[menu.main]]
  name = "quick start"
  weight = 3
  identifier = "quickstart"
  url = "/help/quickstart/"

[[menu.main]]
  name = "help"
  weight = 4
  identifier = "help"
  url = "/help/"

[[menu.main]]
  name = "dev wiki"
  weight = 5
  identifier = "devwiki"
  url = "/wiki/home/"

[[menu.main]]
  name = "screenshots"
  weight = 6
  identifier = "screenshots"
  url = "/screenshots"

[[menu.main]]
  name = "donate"
  weight = 7
  identifier = "donate"
  url = "/donate"

[[menu.main]]
  name = "patreon"
  weight = 8
  identifier = "patreon"
  url = "https://www.patreon.com/yuzuteam"

[Params]
  Tenant = "yuzu"
  BulmaPrimaryShade = "is-dark"
  DiscordURL = "https://discord.gg/u77vRWY"
  TwitterURL = "https://twitter.com/yuzuemu"
  GithubURL = "https://github.com/yuzu-emu/yuzu"
  GoogleAnalyticsTrackingId = "UA-112443698-1"

[Params.fmt]
  ISO8601 = "2006-01-02T15:04:05-07:00"
  Date = "January 02 2006"

[Languages.ptbr]
 title = "yuzu"
 tagline = "Nintendo Switch Emulator"
 description = "yuzu é um emulador de código aberto altamente experimental para o Nintendo Switch."
 weight = 1
  [Languages.en]
    title = "yuzu"
    tagline = "Nintendo Switch Emulator"
    description = "yuzu is a highly experimental open-source emulator for the Nintendo Switch."
    weight = 1

[outputs]
home = [ "HTML", "RSS" ]
section = [ "HTML" ]
